//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.17 at 12:36:38 PM CDT 
//


package org.jenkinsci.plugins.veracodescanner.model.buildinfo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *                 The analysis unit type element contains all the elements and attributes
 *                 that reflect the data we store for a single analysis unit.
 *                 This element contains the following required elements:
 * 
 *                 * status: if the build is published, in progress
 *                 * analysis_type: static, dynamic, manual
 *                 * published_date: date we published if this analysis unit is published
 *                 * published_date: date we published, represented as a UNIX timestamp
 *             
 * 
 * <p>Java class for AnalysisUnitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnalysisUnitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="analysis_type" type="{https://analysiscenter.veracode.com/schema/4.0/buildinfo}AnalysisType" />
 *       &lt;attribute name="published_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="published_date_sec" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="status" type="{https://analysiscenter.veracode.com/schema/4.0/buildinfo}StatusType" />
 *       &lt;attribute name="estimated_scan_hours" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="estimated_delivery_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnalysisUnitType")
public class AnalysisUnitType {

    @XmlAttribute(name = "analysis_type")
    protected AnalysisType analysisType;
    @XmlAttribute(name = "published_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar publishedDate;
    @XmlAttribute(name = "published_date_sec")
    protected BigInteger publishedDateSec;
    @XmlAttribute
    protected StatusType status;
    @XmlAttribute(name = "estimated_scan_hours")
    protected BigInteger estimatedScanHours;
    @XmlAttribute(name = "estimated_delivery_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar estimatedDeliveryDate;

    /**
     * Gets the value of the analysisType property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisType }
     *     
     */
    public AnalysisType getAnalysisType() {
        return analysisType;
    }

    /**
     * Sets the value of the analysisType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisType }
     *     
     */
    public void setAnalysisType(AnalysisType value) {
        this.analysisType = value;
    }

    /**
     * Gets the value of the publishedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublishedDate() {
        return publishedDate;
    }

    /**
     * Sets the value of the publishedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublishedDate(XMLGregorianCalendar value) {
        this.publishedDate = value;
    }

    /**
     * Gets the value of the publishedDateSec property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPublishedDateSec() {
        return publishedDateSec;
    }

    /**
     * Sets the value of the publishedDateSec property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPublishedDateSec(BigInteger value) {
        this.publishedDateSec = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setStatus(StatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the estimatedScanHours property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEstimatedScanHours() {
        return estimatedScanHours;
    }

    /**
     * Sets the value of the estimatedScanHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEstimatedScanHours(BigInteger value) {
        this.estimatedScanHours = value;
    }

    /**
     * Gets the value of the estimatedDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEstimatedDeliveryDate() {
        return estimatedDeliveryDate;
    }

    /**
     * Sets the value of the estimatedDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEstimatedDeliveryDate(XMLGregorianCalendar value) {
        this.estimatedDeliveryDate = value;
    }

}
