//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.17 at 12:36:38 PM CDT 
//


package org.jenkinsci.plugins.veracodescanner.model.buildinfo;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The build type element contains all the elements and attributes
 *                 that reflect the data we store for a single application build.
 *                 This element contains the following attributes:
 * 
 *                 * version:  The version label for the application.
 *                 * build_id: The build identifier we use interally to retrieve information for the build
 *                 * submitter: The name of the account or user who submitted the build.
 *                 * platform:  The platform type for the application.
 *                 * origin:  Who developed the application. collapse down to the four classifications ?
 *                 * lifecycle_stage: Stage this application is in currently
 *                 * policy_name: The name of the policy assigned to this version of the application.
 *                 * policy_version: The version number of the policy assigned to this version
 *                   of the application.
 *                 * policy_compliance_status:  The status of the application relative to the 
 *                   guidelines outlined in the policy.
 *                 * policy_updated_date: The last time an action occurred which might have affected policy compliance.
 *                 * rules_status:  Describes the status of the application relative to the guidelines outlined
 *                   in the policy, without regard to scan frequency guidelines or grace period guidelines.
 *                 * grace_period_expired: If true, indicates that there are outstanding flaws that should 
 *                   have been fixed before the current date based on the policy associated with the application.
 *                 * scan_overdue:  If true, indicates that the amount of time between the most recent analysis
 *                   and the current date is greater than the minimum scan frequency associated with the policy
 *                   assigned to the app.
 *             
 * 
 * <p>Java class for BuildType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuildType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="analysis_unit" type="{https://analysiscenter.veracode.com/schema/4.0/buildinfo}AnalysisUnitType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{https://analysiscenter.veracode.com/schema/4.0/buildinfo}LongRequiredTextType" />
 *       &lt;attribute name="build_id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="submitter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="platform" type="{https://analysiscenter.veracode.com/schema/4.0/buildinfo}PlatformType" />
 *       &lt;attribute name="lifecycle_stage" type="{https://analysiscenter.veracode.com/schema/4.0/buildinfo}LifecycleStageType" />
 *       &lt;attribute name="results_ready" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="policy_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="policy_version" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="policy_compliance_status" type="{https://analysiscenter.veracode.com/schema/4.0/buildinfo}PolicyComplianceType" />
 *       &lt;attribute name="policy_updated_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rules_status" type="{https://analysiscenter.veracode.com/schema/4.0/buildinfo}PolicyComplianceType" />
 *       &lt;attribute name="grace_period_expired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="scan_overdue" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuildType", propOrder = {
    "analysisUnit"
})
public class BuildType {

    @XmlElement(name = "analysis_unit")
    protected List<AnalysisUnitType> analysisUnit;
    @XmlAttribute
    protected String version;
    @XmlAttribute(name = "build_id")
    protected Long buildId;
    @XmlAttribute
    protected String submitter;
    @XmlAttribute
    protected PlatformType platform;
    @XmlAttribute(name = "lifecycle_stage")
    protected LifecycleStageType lifecycleStage;
    @XmlAttribute(name = "results_ready")
    protected Boolean resultsReady;
    @XmlAttribute(name = "policy_name")
    protected String policyName;
    @XmlAttribute(name = "policy_version")
    protected BigInteger policyVersion;
    @XmlAttribute(name = "policy_compliance_status")
    protected PolicyComplianceType policyComplianceStatus;
    @XmlAttribute(name = "policy_updated_date")
    protected String policyUpdatedDate;
    @XmlAttribute(name = "rules_status")
    protected PolicyComplianceType rulesStatus;
    @XmlAttribute(name = "grace_period_expired")
    protected Boolean gracePeriodExpired;
    @XmlAttribute(name = "scan_overdue")
    protected Boolean scanOverdue;

    /**
     * Gets the value of the analysisUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the analysisUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnalysisUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnalysisUnitType }
     * 
     * 
     */
    public List<AnalysisUnitType> getAnalysisUnit() {
        if (analysisUnit == null) {
            analysisUnit = new ArrayList<AnalysisUnitType>();
        }
        return this.analysisUnit;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the buildId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBuildId() {
        return buildId;
    }

    /**
     * Sets the value of the buildId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBuildId(Long value) {
        this.buildId = value;
    }

    /**
     * Gets the value of the submitter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmitter() {
        return submitter;
    }

    /**
     * Sets the value of the submitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmitter(String value) {
        this.submitter = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformType }
     *     
     */
    public PlatformType getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformType }
     *     
     */
    public void setPlatform(PlatformType value) {
        this.platform = value;
    }

    /**
     * Gets the value of the lifecycleStage property.
     * 
     * @return
     *     possible object is
     *     {@link LifecycleStageType }
     *     
     */
    public LifecycleStageType getLifecycleStage() {
        return lifecycleStage;
    }

    /**
     * Sets the value of the lifecycleStage property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifecycleStageType }
     *     
     */
    public void setLifecycleStage(LifecycleStageType value) {
        this.lifecycleStage = value;
    }

    /**
     * Gets the value of the resultsReady property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isResultsReady() {
        return resultsReady;
    }

    /**
     * Sets the value of the resultsReady property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResultsReady(Boolean value) {
        this.resultsReady = value;
    }

    /**
     * Gets the value of the policyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyName() {
        return policyName;
    }

    /**
     * Sets the value of the policyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyName(String value) {
        this.policyName = value;
    }

    /**
     * Gets the value of the policyVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPolicyVersion() {
        return policyVersion;
    }

    /**
     * Sets the value of the policyVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPolicyVersion(BigInteger value) {
        this.policyVersion = value;
    }

    /**
     * Gets the value of the policyComplianceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyComplianceType }
     *     
     */
    public PolicyComplianceType getPolicyComplianceStatus() {
        return policyComplianceStatus;
    }

    /**
     * Sets the value of the policyComplianceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyComplianceType }
     *     
     */
    public void setPolicyComplianceStatus(PolicyComplianceType value) {
        this.policyComplianceStatus = value;
    }

    /**
     * Gets the value of the policyUpdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyUpdatedDate() {
        return policyUpdatedDate;
    }

    /**
     * Sets the value of the policyUpdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyUpdatedDate(String value) {
        this.policyUpdatedDate = value;
    }

    /**
     * Gets the value of the rulesStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyComplianceType }
     *     
     */
    public PolicyComplianceType getRulesStatus() {
        return rulesStatus;
    }

    /**
     * Sets the value of the rulesStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyComplianceType }
     *     
     */
    public void setRulesStatus(PolicyComplianceType value) {
        this.rulesStatus = value;
    }

    /**
     * Gets the value of the gracePeriodExpired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGracePeriodExpired() {
        return gracePeriodExpired;
    }

    /**
     * Sets the value of the gracePeriodExpired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGracePeriodExpired(Boolean value) {
        this.gracePeriodExpired = value;
    }

    /**
     * Gets the value of the scanOverdue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isScanOverdue() {
        return scanOverdue;
    }

    /**
     * Sets the value of the scanOverdue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScanOverdue(Boolean value) {
        this.scanOverdue = value;
    }

}
