//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.17 at 09:27:40 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://analysiscenter.veracode.com/schema/2.0/applist", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.jenkinsci.plugins.veracodescanner.model;
