//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.17 at 02:54:39 PM CDT 
//


package org.jenkinsci.plugins.veracodescanner.model.prescan;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The module type element contains all the elements and attributes
 *                 that reflect the data we store for a module.
 * 
 *                 Elements
 *                 * issue - details on issue related to this module
 * 				* file_issue - details on issue related to an uploaded file
 *             
 * 
 * <p>Java class for ModuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="issue" type="{https://analysiscenter.veracode.com/schema/2.0/prescanresults}IssueType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="file_issue" type="{https://analysiscenter.veracode.com/schema/2.0/prescanresults}FileIssueType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="name" type="{https://analysiscenter.veracode.com/schema/2.0/prescanresults}LongRequiredTextType" />
 *       &lt;attribute name="platform" type="{https://analysiscenter.veracode.com/schema/2.0/prescanresults}LongRequiredTextType" />
 *       &lt;attribute name="size" type="{https://analysiscenter.veracode.com/schema/2.0/prescanresults}LongRequiredTextType" />
 *       &lt;attribute name="status" type="{https://analysiscenter.veracode.com/schema/2.0/prescanresults}DescTextType" />
 *       &lt;attribute name="has_fatal_errors" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModuleType", propOrder = {
    "issue",
    "fileIssue"
})
public class ModuleType {

    protected List<IssueType> issue;
    @XmlElement(name = "file_issue")
    protected List<FileIssueType> fileIssue;
    @XmlAttribute
    protected Long id;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String platform;
    @XmlAttribute
    protected String size;
    @XmlAttribute
    protected String status;
    @XmlAttribute(name = "has_fatal_errors")
    protected Boolean hasFatalErrors;

    /**
     * Gets the value of the issue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IssueType }
     * 
     * 
     */
    public List<IssueType> getIssue() {
        if (issue == null) {
            issue = new ArrayList<IssueType>();
        }
        return this.issue;
    }

    /**
     * Gets the value of the fileIssue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileIssue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileIssue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileIssueType }
     * 
     * 
     */
    public List<FileIssueType> getFileIssue() {
        if (fileIssue == null) {
            fileIssue = new ArrayList<FileIssueType>();
        }
        return this.fileIssue;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the hasFatalErrors property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasFatalErrors() {
        return hasFatalErrors;
    }

    /**
     * Sets the value of the hasFatalErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasFatalErrors(Boolean value) {
        this.hasFatalErrors = value;
    }

}
